package com.example.demo.mapper;

import com.example.demo.dao.BillSchedule;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface BillScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_schedule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_schedule
     *
     * @mbg.generated
     */
    int insert(BillSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_schedule
     *
     * @mbg.generated
     */
    BillSchedule selectByPrimaryKey(Integer billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_schedule
     *
     * @mbg.generated
     */
    List<BillSchedule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BillSchedule record);
}