package com.example.demo.mapper;

import com.example.demo.dao.LevelScore;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface LevelScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_score
     *
     * @mbg.generated
     */
    int insert(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_score
     *
     * @mbg.generated
     */
    LevelScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_score
     *
     * @mbg.generated
     */
    List<LevelScore> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LevelScore record);
    LevelScore selectSumScoreByUserId(String userId);
}