package com.example.demo.mapper;

import com.example.demo.dao.Level;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface LevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated
     */
    int insert(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated
     */
    Level selectByPrimaryKey(Byte level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated
     */
    List<Level> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Level record);
    int selectLevel(int score);
}