package com.example.demo.mapper;

import com.example.demo.dao.PicAwsome;
import java.util.List;

public interface PicAwsomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_awsome
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_awsome
     *
     * @mbg.generated
     */
    int insert(PicAwsome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_awsome
     *
     * @mbg.generated
     */
    PicAwsome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_awsome
     *
     * @mbg.generated
     */
    List<PicAwsome> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_awsome
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PicAwsome record);
}