package com.example.demo.mapper;

import com.example.demo.dao.UserMes;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserMesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mes
     *
     * @mbg.generated
     */
    int insert(UserMes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mes
     *
     * @mbg.generated
     */
    UserMes selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mes
     *
     * @mbg.generated
     */
    List<UserMes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMes record);
    int recharge(String userId, int money);
    int changePassword(String userId, String password);
}