package com.example.demo.mapper;

import com.example.demo.dao.VideoAwsome;
import java.util.List;

public interface VideoAwsomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_awsome
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_awsome
     *
     * @mbg.generated
     */
    int insert(VideoAwsome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_awsome
     *
     * @mbg.generated
     */
    VideoAwsome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_awsome
     *
     * @mbg.generated
     */
    List<VideoAwsome> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_awsome
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoAwsome record);
}