package com.example.demo.mapper;

import com.example.demo.dao.VideoAppMes;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VideoAppMesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_app_mes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_app_mes
     *
     * @mbg.generated
     */
    int insert(VideoAppMes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_app_mes
     *
     * @mbg.generated
     */
    VideoAppMes selectByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_app_mes
     *
     * @mbg.generated
     */
    List<VideoAppMes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_app_mes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoAppMes record);
    int selectMaxappid();
    List<VideoAppMes> selectByCity(String region, int solve);
    List<VideoAppMes> selectByUserId(String userId);
    //查询一个人有多少视频悬赏
    int selectCountByUserId(String userId);
    int changeAppState(int appId, int solve);
    String selectUserIdByAppId(int appId);


}