package com.example.demo.mapper;

import com.example.demo.dao.VideoAnswer;
import org.apache.ibatis.annotations.Mapper;

import java.util.ArrayList;
import java.util.List;

@Mapper
public interface VideoAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer vedioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_answer
     *
     * @mbg.generated
     */
    int insert(VideoAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_answer
     *
     * @mbg.generated
     */
    VideoAnswer selectByPrimaryKey(Integer vedioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_answer
     *
     * @mbg.generated
     */
    List<VideoAnswer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoAnswer record);
//    VideoAnswer selectByUserAndAppId(String userId,int )
    List<VideoAnswer> selectByUserId(String userId);
    List<VideoAnswer> chachong(String userId,int vedioappId);
    int selectSumByAppId(int vedioappId);
    VideoAnswer selectByAnswerUserId(int vedioappId,String userId);
    List<VideoAnswer> selectByVideoAppId(int vedioappId);
    ArrayList<Integer> getAllAuthId();
    int selectCountOfNoVerified();
    ArrayList<VideoAnswer> selectNoVerifyAnswer();
    int changeState(int videoId,int state);
    List<VideoAnswer> selectWeekBestPicAnswer();
    List<VideoAnswer> selectMonthBestPicAnswer();
    int selectCountByUserId(String userId);

    //获取一个请求有多少答案
    int selectCountByAppId(int picappId);
}