package com.example.demo.dao;

import java.util.Date;

public class BillSchedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_schedule.bill_id
     *
     * @mbg.generated
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_schedule.money
     *
     * @mbg.generated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_schedule.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_schedule.app_id
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_schedule.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_schedule.bill_id
     *
     * @return the value of bill_schedule.bill_id
     *
     * @mbg.generated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_schedule.bill_id
     *
     * @param billId the value for bill_schedule.bill_id
     *
     * @mbg.generated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_schedule.money
     *
     * @return the value of bill_schedule.money
     *
     * @mbg.generated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_schedule.money
     *
     * @param money the value for bill_schedule.money
     *
     * @mbg.generated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_schedule.type
     *
     * @return the value of bill_schedule.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_schedule.type
     *
     * @param type the value for bill_schedule.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_schedule.app_id
     *
     * @return the value of bill_schedule.app_id
     *
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_schedule.app_id
     *
     * @param appId the value for bill_schedule.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_schedule.ctime
     *
     * @return the value of bill_schedule.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_schedule.ctime
     *
     * @param ctime the value for bill_schedule.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}