package com.example.demo.dao;

public class Level {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.start_score
     *
     * @mbg.generated
     */
    private Integer startScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.end_score
     *
     * @mbg.generated
     */
    private Integer endScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.level
     *
     * @return the value of level.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.level
     *
     * @param level the value for level.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.start_score
     *
     * @return the value of level.start_score
     *
     * @mbg.generated
     */
    public Integer getStartScore() {
        return startScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.start_score
     *
     * @param startScore the value for level.start_score
     *
     * @mbg.generated
     */
    public void setStartScore(Integer startScore) {
        this.startScore = startScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.end_score
     *
     * @return the value of level.end_score
     *
     * @mbg.generated
     */
    public Integer getEndScore() {
        return endScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.end_score
     *
     * @param endScore the value for level.end_score
     *
     * @mbg.generated
     */
    public void setEndScore(Integer endScore) {
        this.endScore = endScore;
    }
}