package com.example.demo.dao;

public class LevelScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_score.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_score.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_score.login_time
     *
     * @mbg.generated
     */
    private Integer loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_score.answer_score
     *
     * @mbg.generated
     */
    private Integer answerScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_score.id
     *
     * @return the value of level_score.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_score.id
     *
     * @param id the value for level_score.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_score.user_id
     *
     * @return the value of level_score.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_score.user_id
     *
     * @param userId the value for level_score.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_score.login_time
     *
     * @return the value of level_score.login_time
     *
     * @mbg.generated
     */
    public Integer getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_score.login_time
     *
     * @param loginTime the value for level_score.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Integer loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_score.answer_score
     *
     * @return the value of level_score.answer_score
     *
     * @mbg.generated
     */
    public Integer getAnswerScore() {
        return answerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_score.answer_score
     *
     * @param answerScore the value for level_score.answer_score
     *
     * @mbg.generated
     */
    public void setAnswerScore(Integer answerScore) {
        this.answerScore = answerScore;
    }
}