package com.example.demo.dao;

import java.util.Date;

public class PicAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_answer.pic_id
     *
     * @mbg.generated
     */
    private Integer picId;

    public Integer getAwosome() {
        return awosome;
    }

    public void setAwosome(Integer awosome) {
        this.awosome = awosome;
    }

    private Integer state;
    private  Integer awosome;
    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_answer.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_answer.picapp_id
     *
     * @mbg.generated
     */
    private Integer picappId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_answer.pic_adress
     *
     * @mbg.generated
     */
    private String picAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_answer.app_time
     *
     * @mbg.generated
     */
    private Date appTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_answer.pic_id
     *
     * @return the value of pic_answer.pic_id
     *
     * @mbg.generated
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_answer.pic_id
     *
     * @param picId the value for pic_answer.pic_id
     *
     * @mbg.generated
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_answer.user_id
     *
     * @return the value of pic_answer.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_answer.user_id
     *
     * @param userId the value for pic_answer.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_answer.picapp_id
     *
     * @return the value of pic_answer.picapp_id
     *
     * @mbg.generated
     */
    public Integer getPicappId() {
        return picappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_answer.picapp_id
     *
     * @param picappId the value for pic_answer.picapp_id
     *
     * @mbg.generated
     */
    public void setPicappId(Integer picappId) {
        this.picappId = picappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_answer.pic_adress
     *
     * @return the value of pic_answer.pic_adress
     *
     * @mbg.generated
     */
    public String getPicAdress() {
        return picAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_answer.pic_adress
     *
     * @param picAdress the value for pic_answer.pic_adress
     *
     * @mbg.generated
     */
    public void setPicAdress(String picAdress) {
        this.picAdress = picAdress == null ? null : picAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_answer.app_time
     *
     * @return the value of pic_answer.app_time
     *
     * @mbg.generated
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_answer.app_time
     *
     * @param appTime the value for pic_answer.app_time
     *
     * @mbg.generated
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }
}