package com.example.demo.dao;

import java.util.Date;

public class PicAppMes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.app_id
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.app_subject
     *
     * @mbg.generated
     */
    private String appSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.introduce
     *
     * @mbg.generated
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.app_time
     *
     * @mbg.generated
     */
    private Date appTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.money
     *
     * @mbg.generated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.solve
     *
     * @mbg.generated
     */
    private Integer solve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.amazing
     *
     * @mbg.generated
     */
    private Integer amazing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.right_user_id
     *
     * @mbg.generated
     */
    private String rightUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_app_mes.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.app_id
     *
     * @return the value of pic_app_mes.app_id
     *
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.app_id
     *
     * @param appId the value for pic_app_mes.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.app_subject
     *
     * @return the value of pic_app_mes.app_subject
     *
     * @mbg.generated
     */
    public String getAppSubject() {
        return appSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.app_subject
     *
     * @param appSubject the value for pic_app_mes.app_subject
     *
     * @mbg.generated
     */
    public void setAppSubject(String appSubject) {
        this.appSubject = appSubject == null ? null : appSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.introduce
     *
     * @return the value of pic_app_mes.introduce
     *
     * @mbg.generated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.introduce
     *
     * @param introduce the value for pic_app_mes.introduce
     *
     * @mbg.generated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.user_id
     *
     * @return the value of pic_app_mes.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.user_id
     *
     * @param userId the value for pic_app_mes.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.app_time
     *
     * @return the value of pic_app_mes.app_time
     *
     * @mbg.generated
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.app_time
     *
     * @param appTime the value for pic_app_mes.app_time
     *
     * @mbg.generated
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.money
     *
     * @return the value of pic_app_mes.money
     *
     * @mbg.generated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.money
     *
     * @param money the value for pic_app_mes.money
     *
     * @mbg.generated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.solve
     *
     * @return the value of pic_app_mes.solve
     *
     * @mbg.generated
     */
    public Integer getSolve() {
        return solve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.solve
     *
     * @param solve the value for pic_app_mes.solve
     *
     * @mbg.generated
     */
    public void setSolve(Integer solve) {
        this.solve = solve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.amazing
     *
     * @return the value of pic_app_mes.amazing
     *
     * @mbg.generated
     */
    public Integer getAmazing() {
        return amazing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.amazing
     *
     * @param amazing the value for pic_app_mes.amazing
     *
     * @mbg.generated
     */
    public void setAmazing(Integer amazing) {
        this.amazing = amazing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.right_user_id
     *
     * @return the value of pic_app_mes.right_user_id
     *
     * @mbg.generated
     */
    public String getRightUserId() {
        return rightUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.right_user_id
     *
     * @param rightUserId the value for pic_app_mes.right_user_id
     *
     * @mbg.generated
     */
    public void setRightUserId(String rightUserId) {
        this.rightUserId = rightUserId == null ? null : rightUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_app_mes.region
     *
     * @return the value of pic_app_mes.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_app_mes.region
     *
     * @param region the value for pic_app_mes.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }
}