package com.example.demo.dao;

import java.util.Date;

public class TimeSatistic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_satistic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_satistic.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_satistic.loginTime
     *
     * @mbg.generated
     */
    private Date logintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_satistic.latestOpTime
     *
     * @mbg.generated
     */
    private Date latestoptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_satistic.id
     *
     * @return the value of time_satistic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_satistic.id
     *
     * @param id the value for time_satistic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_satistic.user_id
     *
     * @return the value of time_satistic.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_satistic.user_id
     *
     * @param userId the value for time_satistic.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_satistic.loginTime
     *
     * @return the value of time_satistic.loginTime
     *
     * @mbg.generated
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_satistic.loginTime
     *
     * @param logintime the value for time_satistic.loginTime
     *
     * @mbg.generated
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_satistic.latestOpTime
     *
     * @return the value of time_satistic.latestOpTime
     *
     * @mbg.generated
     */
    public Date getLatestoptime() {
        return latestoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_satistic.latestOpTime
     *
     * @param latestoptime the value for time_satistic.latestOpTime
     *
     * @mbg.generated
     */
    public void setLatestoptime(Date latestoptime) {
        this.latestoptime = latestoptime;
    }
}