package com.example.demo.dao;

public class UserMes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.money
     *
     * @mbg.generated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.ask
     *
     * @mbg.generated
     */
    private Integer ask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.answer
     *
     * @mbg.generated
     */
    private Integer answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mes.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.user_id
     *
     * @return the value of user_mes.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.user_id
     *
     * @param userId the value for user_mes.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.email
     *
     * @return the value of user_mes.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.email
     *
     * @param email the value for user_mes.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.signature
     *
     * @return the value of user_mes.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.signature
     *
     * @param signature the value for user_mes.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.phone
     *
     * @return the value of user_mes.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.phone
     *
     * @param phone the value for user_mes.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.money
     *
     * @return the value of user_mes.money
     *
     * @mbg.generated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.money
     *
     * @param money the value for user_mes.money
     *
     * @mbg.generated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.region
     *
     * @return the value of user_mes.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.region
     *
     * @param region the value for user_mes.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.ask
     *
     * @return the value of user_mes.ask
     *
     * @mbg.generated
     */
    public Integer getAsk() {
        return ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.ask
     *
     * @param ask the value for user_mes.ask
     *
     * @mbg.generated
     */
    public void setAsk(Integer ask) {
        this.ask = ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.answer
     *
     * @return the value of user_mes.answer
     *
     * @mbg.generated
     */
    public Integer getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.answer
     *
     * @param answer the value for user_mes.answer
     *
     * @mbg.generated
     */
    public void setAnswer(Integer answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.password
     *
     * @return the value of user_mes.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.password
     *
     * @param password the value for user_mes.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mes.nickname
     *
     * @return the value of user_mes.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mes.nickname
     *
     * @param nickname the value for user_mes.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }
}