package com.example.demo.dao;

import java.util.Date;

public class VideoAppMes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.app_id
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.app_subject
     *
     * @mbg.generated
     */
    private String appSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.asktime
     *
     * @mbg.generated
     */
    private Date asktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.solve
     *
     * @mbg.generated
     */
    private Integer solve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.amazing
     *
     * @mbg.generated
     */
    private Integer amazing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.money
     *
     * @mbg.generated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.right_user_id
     *
     * @mbg.generated
     */
    private String rightUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_app_mes.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.app_id
     *
     * @return the value of video_app_mes.app_id
     *
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.app_id
     *
     * @param appId the value for video_app_mes.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.app_subject
     *
     * @return the value of video_app_mes.app_subject
     *
     * @mbg.generated
     */
    public String getAppSubject() {
        return appSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.app_subject
     *
     * @param appSubject the value for video_app_mes.app_subject
     *
     * @mbg.generated
     */
    public void setAppSubject(String appSubject) {
        this.appSubject = appSubject == null ? null : appSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.introduction
     *
     * @return the value of video_app_mes.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.introduction
     *
     * @param introduction the value for video_app_mes.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.user_id
     *
     * @return the value of video_app_mes.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.user_id
     *
     * @param userId the value for video_app_mes.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.asktime
     *
     * @return the value of video_app_mes.asktime
     *
     * @mbg.generated
     */
    public Date getAsktime() {
        return asktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.asktime
     *
     * @param asktime the value for video_app_mes.asktime
     *
     * @mbg.generated
     */
    public void setAsktime(Date asktime) {
        this.asktime = asktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.solve
     *
     * @return the value of video_app_mes.solve
     *
     * @mbg.generated
     */
    public Integer getSolve() {
        return solve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.solve
     *
     * @param solve the value for video_app_mes.solve
     *
     * @mbg.generated
     */
    public void setSolve(Integer solve) {
        this.solve = solve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.amazing
     *
     * @return the value of video_app_mes.amazing
     *
     * @mbg.generated
     */
    public Integer getAmazing() {
        return amazing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.amazing
     *
     * @param amazing the value for video_app_mes.amazing
     *
     * @mbg.generated
     */
    public void setAmazing(Integer amazing) {
        this.amazing = amazing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.money
     *
     * @return the value of video_app_mes.money
     *
     * @mbg.generated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.money
     *
     * @param money the value for video_app_mes.money
     *
     * @mbg.generated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.right_user_id
     *
     * @return the value of video_app_mes.right_user_id
     *
     * @mbg.generated
     */
    public String getRightUserId() {
        return rightUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.right_user_id
     *
     * @param rightUserId the value for video_app_mes.right_user_id
     *
     * @mbg.generated
     */
    public void setRightUserId(String rightUserId) {
        this.rightUserId = rightUserId == null ? null : rightUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_app_mes.region
     *
     * @return the value of video_app_mes.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_app_mes.region
     *
     * @param region the value for video_app_mes.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }
}