package com.example.demo.dao;

import java.util.Date;

public class VideoAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_answer.vedio_id
     *
     * @mbg.generated
     */
    private Integer vedioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_answer.vedioapp_id
     *
     * @mbg.generated
     */
    private Integer vedioappId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_answer.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_answer.vedio_adress
     *
     * @mbg.generated
     */
    private String vedioAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_answer.subtime
     *
     * @mbg.generated
     */
    private Date subtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_answer.vedio_id
     *
     * @return the value of video_answer.vedio_id
     *
     * @mbg.generated
     */
    public Integer getVedioId() {
        return vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_answer.vedio_id
     *
     * @param vedioId the value for video_answer.vedio_id
     *
     * @mbg.generated
     */
    public void setVedioId(Integer vedioId) {
        this.vedioId = vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_answer.vedioapp_id
     *
     * @return the value of video_answer.vedioapp_id
     *
     * @mbg.generated
     */
    public Integer getVedioappId() {
        return vedioappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_answer.vedioapp_id
     *
     * @param vedioappId the value for video_answer.vedioapp_id
     *
     * @mbg.generated
     */
    public void setVedioappId(Integer vedioappId) {
        this.vedioappId = vedioappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_answer.user_id
     *
     * @return the value of video_answer.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_answer.user_id
     *
     * @param userId the value for video_answer.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_answer.vedio_adress
     *
     * @return the value of video_answer.vedio_adress
     *
     * @mbg.generated
     */
    public String getVedioAdress() {
        return vedioAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_answer.vedio_adress
     *
     * @param vedioAdress the value for video_answer.vedio_adress
     *
     * @mbg.generated
     */
    public void setVedioAdress(String vedioAdress) {
        this.vedioAdress = vedioAdress == null ? null : vedioAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_answer.subtime
     *
     * @return the value of video_answer.subtime
     *
     * @mbg.generated
     */
    public Date getSubtime() {
        return subtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_answer.subtime
     *
     * @param subtime the value for video_answer.subtime
     *
     * @mbg.generated
     */
    public void setSubtime(Date subtime) {
        this.subtime = subtime;
    }
}